version: 0.2

env:
  parameter-store:
    SHMENKINS_API_URL: "shmenkins_api_url"

phases:
  install:
    commands:
      - make init
  pre_build:
    commands:
      - make config
  build:
    commands:
      - make test
